final String _apiBaseUrl = /* 'http://secretservice.ddns.net:8080/' */ 'http://10.0.2.2:8080/';
final String loginUrl = _apiBaseUrl + 'login'; 
final String registerUrl = _apiBaseUrl + 'api/users/register';
final String usersUrl = _apiBaseUrl + 'api/users';
final String activateUserUrl = _apiBaseUrl + 'api/users/activate/'; // + userId
final String deactivateUserUrl = _apiBaseUrl + 'api/users/deactivate/'; // + userId
final String getUserByEmailUrl = _apiBaseUrl + 'api/users/email/'; // + email
final String requestSitUrl = _apiBaseUrl + 'api/sits/create';
final String browseSitsUrl = _apiBaseUrl + 'api/sits';
final String editUserUrl = _apiBaseUrl + 'api/users/edit';
final String addAnimalUrl = _apiBaseUrl + 'api/animals';
final String getAnimalsUrl = _apiBaseUrl + 'api/animals';